{{- if .Values.restore.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: restore
  annotations:
    "helm.sh/hook": post-install  # Execute after all resources are installed
    "helm.sh/hook-weight": "5"   # Control the order of hook execution
    "helm.sh/hook-delete-policy": hook-succeeded  # Delete the job if it succeeds
spec:
  template:
    spec:
      affinity: 
        {{ .Values.global.affinity | toYaml | nindent 8 }}
      serviceAccountName: sa-mysql-restore
      containers:
      - name: restore-mysqldb
        image: {{ .Values.restore.image }}
        imagePullPolicy: Always
        env:
        - name: MYSQL_HOST
          value: {{ include "common.names.fullname" . }}-primary.{{ .Release.Namespace }}.svc.cluster.local
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "common.names.fullname" . }}
              key: mysql-root-password
        - name: MYSQL_NON_ROOT_USER
          value: {{ .Values.auth.username }}
        - name: MYSQL_BUCKET_RESTORE_URI
          valueFrom:
            secretKeyRef:
              name: mysql-bucket-uri-restore
              key: MYSQL_BUCKET_URI
        - name: RESTORE_FILE_NAME
          value: {{ .Values.restore.file_name }}
        - name: RESTORE_FROM
          value: {{ .Values.restore.bucket_provider_type }}
        - name: AWS_DEFAULT_REGION
          value: {{ .Values.restore.aws_default_region }}
        resources: 
          {{ .Values.restore.resources | toYaml | nindent 14 }}
      restartPolicy: Never
  backoffLimit: 4
{{- end }}
